### ISSUE TITLE
Hide TabBars

### ISSUE THREAD

**Issue by saroar** [darrarski/swift-composable-app-example#1] opened 2021-04-06 13:14 UTC
https://github.com/AddaMeSPB/AddaMeIOSSwiftUI/blob/master/AddaMeIOS/App/AppTabView.swift#L46
i have some custom types for hiding tab bar but quis was how to use this into composable-a...

you send me this link https://stackoverflow.com/questions/58444689/swiftui-hide-tabbar-in-subview

thanks

**Comment by darrarski** [comment] 2021-04-06 18:12
I'm afraid I don't understand your question. I saw your code and it looks like you’re not using ComposableArchitecture. If you want to using it, I recommend to start with [these videos](https://www.pointfree.co/collections/composable-architecture/a-tour-of-the-composable-architecture) (available for free). I also recommend the whole [Pointfree](https://www.pointfree.co/) series if you want to learn more. In case you have some specific questions about ComposableArchitecture, you can ask it on the [GitHub Discussions](https://github.com/pointfreeco/swift-composable-architecture/discussions) page.

**Comment by saroar** [comment] 2021-04-06 19:00
i Pointfree regular subscriber :) (i  love their videos)  i show my code which is working but without composable architecture, my quis was how we can do it with composable architecture  
i am a big fan of open source so i create one big project fully open source which I send u a link to (swift ios + swift back end)
so i am trying to convert my full app with composable architecture

**Comment by darrarski** [comment] 2021-04-06 20:18
I would start by defining the state and actions for your view. Then you can create a reducer and add `Store<YourState, YourAction>` to the view. Brandon and Stephen explain it really well on Point-Free videos. Good luck!

**Comment by saroar** [comment] 2021-04-12 13:45
hi, do you have the same problem with your app?

```
received action:
  TabsAction.event(
    EventsAction.onAppear
  )
  (No state changes)

received action:
  TabsAction.event(
    EventsAction.onAppear
  )
  (No state changes)

received action:
  TabsAction.event(
    EventsAction.locationResponse(
      Result<DelegateEvent, Never>.success(
        DelegateEvent.didChangeAuthorization(
          CLAuthorizationStatus.CLAuthorizationStatus
        )
      )
    )
  )
  (No state changes)

received action:
  TabsAction.event(
    EventsAction.locationResponse(
      Result<DelegateEvent, Never>.success(
        DelegateEvent.didChangeAuthorization(
          CLAuthorizationStatus.CLAuthorizationStatus
        )
      )
    )
  )
  (No state changes)
```

i mean call two times root view

**Comment by darrarski** [comment] 2021-04-12 15:34
It's hard to tell without the context what's going on. Please be more descriptive when asking questions (for example: provide a list of steps to reproduce).

I will take a look at the problem you experienced and let you know if I manage to reproduce it and investigate later today.

**Comment by darrarski** [comment] 2021-04-12 16:11
I manage to reproduce the problem and created a dedicated issue for it: #2. Closing.

**Closed as completed by darrarski** 2021-04-12 16:11 UTC
